# Generated by Django 4.2 on 2023-04-05 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songdecks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='playercard',
            name='discarded_at',
        ),
        migrations.RemoveField(
            model_name='playercard',
            name='played_at',
        ),
        migrations.AddField(
            model_name='playercard',
            name='discarded_this_round',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='playercard',
            name='drawn_this_round',
            field=models.BooleanField(default=False),
        ),
    ]
