# Generated by Django 4.2 on 2023-05-16 01:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songdecks', '0002_remove_playercard_discarded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardtemplate',
            name='replaces',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='songdecks.cardtemplate'),
        ),
        migrations.AddField(
            model_name='faction',
            name='neutral',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='round',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
