# Generated by Django 4.2 on 2023-05-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songdecks', '0003_cardtemplate_replaces_faction_neutral_game_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='moderator',
            field=models.BooleanField(default=False),
        ),
    ]
