# Generated by Django 4.2 on 2023-12-20 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songdecks', '0006_task_priority'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorited_proposals', to='songdecks.profile'),
        ),
        migrations.AddField(
            model_name='task',
            name='favorited_by',
            field=models.ManyToManyField(blank=True, related_name='favorited_tasks', to='songdecks.profile'),
        ),
    ]
