# Generated by Django 4.2 on 2023-12-26 17:12

from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):

    dependencies = [
        ('songdecks', '0012_keywordpair'),
    ]

    operations = [
        migrations.CreateModel(
            name='KeywordType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('keyword_type'), models.Model),
        ),
        migrations.AlterField(
            model_name='keywordpair',
            name='keyword',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AddField(
            model_name='keywordpair',
            name='keyword_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='songdecks.keywordtype'),
        ),
    ]
