# Generated by Django 4.2 on 2023-12-27 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songdecks', '0013_keywordtype_alter_keywordpair_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='keywordpair',
            name='keyword_types',
            field=models.ManyToManyField(blank=True, related_name='keyword_pairs', to='songdecks.keywordtype'),
        ),
    ]
