# Generated by Django 4.2 on 2023-12-27 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songdecks', '0014_keywordpair_keyword_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='keywordpair',
            name='keyword_type',
        ),
    ]
