# Generated by Django 4.2 on 2023-12-28 16:13

from django.db import migrations, models
import django.db.models.deletion
import django_prometheus.models


class Migration(migrations.Migration):

    dependencies = [
        ('songdecks', '0015_remove_keywordpair_keyword_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points_cost', models.PositiveIntegerField()),
                ('image_url', models.URLField(max_length=500)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songdecks.faction')),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('attachment'), models.Model),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points_cost', models.PositiveIntegerField()),
                ('unit_type', models.CharField(choices=[('infantry', 'Infantry'), ('cavalry', 'Cavalry'), ('monster', 'Monster'), ('war_machine', 'War Machine')], max_length=20)),
                ('image_url', models.URLField(max_length=500)),
                ('attachments', models.ManyToManyField(blank=True, null=True, to='songdecks.attachment')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songdecks.faction')),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('unit'), models.Model),
        ),
        migrations.CreateModel(
            name='NCU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points_cost', models.PositiveIntegerField()),
                ('image_url', models.URLField(max_length=500)),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songdecks.faction')),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('ncu'), models.Model),
        ),
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('points_allowed', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_draft', models.BooleanField(default=False)),
                ('is_public', models.BooleanField(default=False)),
                ('is_valid', models.BooleanField(default=False)),
                ('commander', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songdecks.commander')),
                ('faction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songdecks.faction')),
                ('ncus', models.ManyToManyField(blank=True, null=True, to='songdecks.ncu')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_lists', to='songdecks.profile')),
                ('shared_from', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='songdecks.profile')),
                ('units', models.ManyToManyField(blank=True, null=True, to='songdecks.unit')),
            ],
            bases=(django_prometheus.models.ExportModelOperationsMixin('list'), models.Model),
        ),
        migrations.AddField(
            model_name='game',
            name='owner_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='songdecks.list'),
        ),
    ]
