# Generated by Django 4.2 on 2023-12-28 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songdecks', '0017_alter_list_ncus_alter_list_units_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attachment',
            old_name='image_url',
            new_name='img_url',
        ),
        migrations.RenameField(
            model_name='ncu',
            old_name='image_url',
            new_name='img_url',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='image_url',
            new_name='img_url',
        ),
        migrations.AddField(
            model_name='attachment',
            name='type',
            field=models.CharField(choices=[('infantry', 'Infantry'), ('cavalry', 'Cavalry'), ('monster', 'Monster'), ('war_machine', 'War Machine')], default='infantry', max_length=20),
            preserve_default=False,
        ),
    ]
