# Generated by Django 4.2 on 2023-12-31 21:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songdecks', '0019_attachment_main_url_ncu_main_url_unit_main_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='list',
            name='commander',
        ),
        migrations.AddField(
            model_name='attachment',
            name='is_commander',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='commander',
            name='commander_type',
            field=models.CharField(choices=[('unit', 'Unit'), ('attachment', 'Attachment')], default='attachment', max_length=20),
        ),
        migrations.AddField(
            model_name='unit',
            name='is_commander',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ListUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('attachments', models.ManyToManyField(blank=True, to='songdecks.attachment')),
                ('commander', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='songdecks.commander')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_list', to='songdecks.list')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songdecks.unit')),
            ],
        ),
        migrations.CreateModel(
            name='ListNCU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ncu_list', to='songdecks.list')),
                ('ncu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='songdecks.ncu')),
            ],
        ),
        migrations.AlterField(
            model_name='list',
            name='ncus',
            field=models.ManyToManyField(blank=True, related_name='list_ncus', to='songdecks.listncu'),
        ),
        migrations.AlterField(
            model_name='list',
            name='units',
            field=models.ManyToManyField(blank=True, related_name='list_units', to='songdecks.listunit'),
        ),
    ]
