# Generated by Django 4.2 on 2024-01-07 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songdecks', '0020_remove_list_commander_attachment_is_commander_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='is_commander',
        ),
        migrations.AddField(
            model_name='attachment',
            name='attachment_type',
            field=models.CharField(choices=[('generic', 'Generic'), ('character', 'Character'), ('commander', 'Commander')], default='generic', max_length=20),
        ),
    ]
