# Generated by Django 4.2 on 2024-01-08 03:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('songdecks', '0021_remove_attachment_is_commander_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='list',
            name='commander',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='songdecks.commander'),
            preserve_default=False,
        ),
    ]
