# Generated by Django 4.2 on 2024-01-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songdecks', '0023_faction_can_use_neutral'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='attachments',
        ),
    ]
