# Generated by Django 4.2 on 2024-01-14 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songdecks', '0025_remove_listunit_quantity_unit_is_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='is_unique',
        ),
        migrations.AddField(
            model_name='unit',
            name='max_in_list',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
