# Generated by Django 4.2 on 2024-01-14 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songdecks', '0026_remove_unit_is_unique_unit_max_in_list'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='is_commander',
        ),
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('commander', 'Commander'), ('commander_unit', 'Commander Unit'), ('generic', 'Generic')], default='generic', max_length=20),
        ),
    ]
