# Generated by Django 4.2 on 2024-01-23 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songdecks', '0028_unit_attached_commander'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tester',
            field=models.BooleanField(default=False),
        ),
    ]
