# Generated by Django 4.2 on 2024-01-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songdecks', '0029_profile_tester'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='session_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
