# Generated by Django 5.0.3 on 2024-03-16 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songdecks', '0030_profile_session_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='is_adaptive',
            field=models.BooleanField(default=False),
        ),
    ]
