global:
  scrape_interval: 10s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: songdecks_local
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - 'web'