global:
  scrape_interval: 10s
  scrape_timeout: 10s

rule_files:
  - alert.yml

scrape_configs:
  - job_name: songdecks_prod
    metrics_path: /metrics
    scheme: https
    static_configs:
      - targets:
          - 'asoiaf-decks.com'