# fly.toml app configuration file generated for song-decks on 2025-05-10T23:00:20-06:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'song-decks'
primary_region = 'den'
console_command = '/code/manage.py shell'

[build]
  [build.args]
    TARGET_ENV = "flyio"

[env]
  PORT = '8000'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[processes]
  app = "gunicorn --bind 0.0.0.0:8000 --workers 2 songdecks.wsgi"

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 2

[[statics]]
  guest_path = '/code/static'
  url_prefix = '/static/'
